#!/bin/bash

# send email
export HOME=~
EMAIL_HOST=$(curl -s checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//')
EMAIL_EXEC="mail"
EMAIL_ACCOUNT="gmail"
EMAIL_SUBJECT="Smartd has detected $SMARTD_FAILTYPE error on $SMARTD_DEVICE"
EMAIL_BODY="
Smartd error details:
Error type:            $SMARTD_FAILTYPE
Device node:         $SMARTD_DEVICESTRING
Date occurred:       $SMARTD_TFIRST
Below is the full original message generated by smartd:
------------------------------------------------------------------------------------------
$SMARTD_FULLMESSAGE
------------------------------------------------------------------------------------------

>> this message was auto generated and sent by a bash script <<"
echo "$EMAIL_BODY" | $EMAIL_EXEC -A $EMAIL_ACCOUNT -s "$EMAIL_SUBJECT" $SMARTD_ADDRESS

# notify user
wall "$SMARTD_MESSAGE"
